version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: chaves.frontend

  php:
    build:
      context: ./php
    ports:
      - 8001:8000
    restart: unless-stopped
    container_name: chaves.php

  ruby:
    build:
      context: ./ruby
    ports:
      - 8002:8000
    restart: unless-stopped
    container_name: chaves.ruby

  node:
    build:
      context: ./node
    ports:
      - 8003:3000
    restart: unless-stopped
    container_name: chaves.node

  python:
    build:
      context: ./python
    ports:
      - 8004:8000
    restart: unless-stopped
    container_name: chaves.python

  lua:
    build:
      context: ./lua
    ports:
      - 8005:8000
    restart: unless-stopped
    container_name: chaves.lua
  
  perl:
    build:
      context: ./perl
    ports:
      - 8006:8000
    restart: unless-stopped
    container_name: chaves.perl
  
  go:
    build:
      context: ./go
    ports:
      - 8007:8000
    restart: unless-stopped
    container_name: chaves.go
  
  java:
    build:
      context: ./java
    ports:
      - 8008:8000
    restart: unless-stopped
    container_name: chaves.java
  
  swift:
    build:
      context: ./swift
    ports:
      - 8009:8000
    restart: unless-stopped
    container_name: chaves.swift