services:
  frontend:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./phrases:/usr/share/nginx/html/phrases
    container_name: chaves.frontend

  php:
    build:
      context: ./php
    ports:
      - 8001:8000
    restart: unless-stopped
    container_name: chaves.php
    volumes:
      - ./phrases:/app/phrases

  ruby:
    build:
      context: ./ruby
    ports:
      - 8002:8000
    restart: unless-stopped
    container_name: chaves.ruby
    volumes:
      - ./phrases:/app/phrases

  node:
    build:
      context: ./node
    ports:
      - 8003:3000
    restart: unless-stopped
    container_name: chaves.node
    volumes:
      - ./phrases:/app/phrases

  python:
    build:
      context: ./python
    ports:
      - 8004:8000
    restart: unless-stopped
    container_name: chaves.python
    volumes:
      - ./phrases:/app/phrases

  lua:
    build:
      context: ./lua
    ports:
      - 8005:8000
    restart: unless-stopped
    container_name: chaves.lua
    volumes:
      - ./phrases:/app/phrases
  
  perl:
    build:
      context: ./perl
    ports:
      - 8006:8000
    restart: unless-stopped
    container_name: chaves.perl
    volumes:
      - ./phrases:/app/phrases
  
  go:
    build:
      context: ./go
    ports:
      - 8007:8000
    restart: unless-stopped
    container_name: chaves.go
    volumes:
      - ./phrases:/app/phrases
  
  java:
    build:
      context: ./java
    ports:
      - 8008:8000
    restart: unless-stopped
    container_name: chaves.java
    volumes:
      - ./phrases:/phrases
  
  swift:
    build:
      context: ./swift
    ports:
      - 8009:8000
    restart: unless-stopped
    container_name: chaves.swift
    volumes:
      - ./phrases:/app/phrases

  shell-script:
    build:
      context: ./shell-script
    ports:
      - 8010:80
    restart: unless-stopped
    container_name: chaves.shell-script
    volumes:
      - ./phrases:/usr/src/jaiminho/phrases
    
  crystal:
    build:
      context: ./crystal
    ports:
      - 8011:80
    restart: unless-stopped
    container_name: chaves.crystal
    volumes:
      - ./phrases:/usr/src/app/phrases
  
  typescript:
    build:
      context: ./typescript
    ports:
      - 8012:8000
    restart: unless-stopped
    container_name: chaves.typescript
    volumes:
      - ./phrases:/app/phrases
  
  coffeescript:
    build:
      context: ./coffeescript
    ports:
      - 8013:8000
    restart: unless-stopped
    container_name: chaves.coffeescript
    volumes:
      - ./phrases:/app/phrases
  
  cplusplus:
    build:
      context: ./cplusplus
    ports:
      - 8014:8080
    restart: unless-stopped
    container_name: chaves.cplusplus
    volumes:
      - ./phrases:/app/phrases